author: Created by - Kushaan Gupta
title: SWANAND LAB @ IISC
description: >
  Centre for Neuroscience, Indian Institute of Science, Bangalore,
  India, 560012.

markdown: kramdown
theme: minima

header_pages:
  - team.md
  - research.md
  - publications.md
  - careers.md
  - news.md

# networking
email: swanand@iisc.ac.in
twitter_username: LabSwanand
github_username:  swanandlab
scholar: PRwLoqkAAAAJ
orcid: 0000-0002-2539-366X

show_excerpts: true
